output_folder_dir_path: "Output"

# hashmap <name of class based on dataset, 3D model for it>
interactable_objs:
    "sports ball": "3D_Models/"

# for object detection
yolo_params:
    checkpoint_file: "Data/yolov8x.pt"

    dataset_file: "Data/coco.yaml"

    # obj below will not be included
    confidence_score: 0.1

    # measure of area overlap between two bounding box. 0 (no overlap) to 1 (complete overlap).
    # If got overlap (amt >= value) we will disregard the bounding box with lower confidence score
    intersection_over_union: 0.75

    # can use cuda:{gpuIndex} or cpu
    device: "cuda:0"

# Deepsort, Object tracking model, settings
deepsort_params:
    checkpoint_file: "./Data/mars-small128.pb"

    # if false, uses euclidean distance
    use_cosine_distance: True

    # higher max_cosing_distance value means less restrictive, larger values are considered invalid
    max_distance: 0.7

    # maximum allowavle overlap. So if 0.8, it means overlap from current detection and previous has to be 80%
    max_iou_distance: 0.7

    # Maximum number of missed misses before a track is deleted.
    max_age: 30

    # Number of frames that a track remains in initialization phase.
    n_init: 1

vibe_params:
    checkpoint_file: ""

    batch_size: 17

    runSimplify: True

    # Use 1 euro filter to smooth the results
    smooth_results: True
    smooth_min_cutoff: 0.004
    smooth_beta: 1.5

# parameters related to attaching obj to an existing keypoint
obj_keypoint_attachment_params:
    max_distance: 90 # pixel distance

    attachable_keypoints: [4, 7] # keypoints the object can attach to. Based on Renderin/lib/data_utils get_spin_joint_names()

obj_smoothing:
    max_missing_frames: 10 # maximum number of frame an obj can go missing before it is deemed out of frame

render_output:
    # Whether the models would be in wireframe mode
    isWireframe: True

    # Overlay the animation and models over the original video
    renderOnOriVid: True
